name: Build master branch

on:
  push:
    branches:
      - main

jobs:
  build-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
      - name: Build main
        run: |
          ./mvnw clean verify
